spring:
  application:
    name: consumer-producer-service
    version: 1.0.0
  profiles:
    active: default

logging:
  path: /tmp

---
spring:
  profiles: default
  kafka:
    consumer:
      topics: event-input
      bootstrap-servers: localhost:9092
      group-id: event-listener
      poll.timeout.ms: 100
      properties:
        allow.auto.create.topics: false
        enable.auto.commit: false
        auto.offset.reset: earliest
        max.poll.records: 5
        max.poll.interval.ms: 300
    producer:
      topics:
        output: event-output
        error: event-error
      bootstrap-servers: localhost:9092
      properties:
        acks: 1
        linger.ms: 1000
        retries: 100
        retry.backoff.ms: 1000

---
spring:
  profiles: dev
  kafka:
    properties:
      security:
        protocol: SSL
    consumer:
      topics:
      bootstrap-servers:
      group-id: event-listener
      poll.timeout.ms: 100
      ssl:
        key-store-location: file:src/main/resources/keystore.jks
        key-store-password:
        trust-store-location: file:src/main/resources/truststore.jks
        trust-store-password:
      properties:
        allow.auto.create.topics: false
        enable.auto.commit: false
        auto.offset.reset: earliest
        max.poll.records: 200
        max.poll.interval.ms: 300000
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:
    producer:
      topics:
        request:
        error:
        indexing:
      bootstrap-servers: 
      ssl:
        trust-store-location: file:src/main/resources/truststore.jks
        trust-store-password:
      properties:
        acks: 1
        delivery.timeout.ms: 18000000
        request.timeout.ms: 3600000
        linger.ms: 1000
        max.block.ms: 18000000
        max.request.size: 16777216
        retries: 100
        retry.backoff.ms: 1000
        security:
          protocol: SASL_SSL
        sasl:
          mechanism: SCRAM-SHA-256
          jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="" password="";
        ssl.endpoint.identification.algorithm:

---
spring:
  profiles: test

---
spring:
  profiles: stage

---
spring:
  profiles: prod
