apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer-producer-service
  name: consumer-producer-service
  namespace: dev
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8089"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: port-1
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: port-2
      port: 8089
      protocol: TCP
      targetPort: 8089
  selector:
    app: consumer-producer-service
  sessionAffinity: None
  type: NodePort
